### ISSUE TITLE
Interested in PDART proposal to convert MarsNet to Python?

### ISSUE THREAD

**Issue by michaelaye** [leonpalafox/CNNPlanetaryScience#3]
Hi there!
Would you be interested in collaborating on a NASA ROSES PDART proposal to get funded to convert this pipeline to Python?
The only thing I would need to understand for feasibility is how MarsNet makes use of the GPU, not sure we have as good modules available for that in Python.
Can you tell me what exact math operations are being sent to the GPU? 
There's obviously some CUDA and OpenCL libraries out there, but possibly the Matlab module is on a higher level than that, more user-oriented?

I have seen that you work at LPL, I'm an (unfunded) HiRISE team member, so I work a lot with HiRISE data, hence my interest in MarsNet.
I guess you are familiar with the ROSES PDART proposal call? If not, here's the link to it:

https://nspires.nasaprs.com/external/viewrepositorydocument?cmdocumentid=611716&solicitationId={AA7317BB-94CF-C199-1A47-9AFE173D1216}&viewSolicitationDocument=1

**Comment by leonpalafox** [comment]
Hi,
Is it your interest to solely transform the pipeline to python? Actually, I think its' easier to use things like Tensorflow or Caffe.

What plan do you have in general for the proposal?

**Comment by michaelaye** [comment]
Sorry, I never got back  to you! I was in a proposal writing frenzy, I guess. The advice to use rather tensorflow is the right one, especially these days. I'm also looking at fast.ai.
